spring:
  datasource:
    # Convert Render DATABASE_URL to JDBC automatically if needed
    url: ${JDBC_DATABASE_URL:${DB_URL:jdbc:postgresql://localhost:5432/findy_db}}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:deepak@2004}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:admin}

server:
  port: ${PORT:8081}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

jwt:
  secret: ${JWT_SECRET:default_secret}
  expiration: 86400000 # 24 hours

logging:
  level:
    com.example.findy: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
