spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/findy_db
    username: postgres
    password: deepak@2004
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    user:
      name: admin
      password: admin

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

jwt:
  secret: your-secret-key-here-make-it-long-and-secure
  expiration: 86400000 # 24 hours

logging:
  level:
    com.example.findy: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
